### ISSUE TITLE
Hi @YyzHarry,

### ISSUE THREAD

**Issue by ytkmy5555** [YyzHarry/imbalanced-regression#17]
Hi @YyzHarry,
I want to use your code of LDS to solve my problem,now I have a question to ask you：whether the input data format of LDS must be csv？Is npz format data OK？can it be applied to high-dimensional data？ I would appreciate it if you could give me some guidance.

**Comment by kaiwenzha** [comment]
Hi @ytkmy5555 Thanks for your interest. The input data format is flexible as long as you read the model inputs correctly. You can always convert them to each other. It can be applied to high-dimensional data.

**Comment by ytkmy5555** [comment]
Hi，thank you very much for your reply。I successfully applied your LDS code to my data。However，it does make the data look closer overall, but the RMSE and MAE of the test increased.I want to know what caused this result.I would appreciate it if you could give me some answers.
The frist picture without LDS but the second picture used LDS code.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YyzHarry/imbalanced-regression"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月20日(星期天) 上午9:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YyzHarry/imbalanced-regression] Hi @YyzHarry, (Issue #17)





 
Hi @ytkmy5555 Thanks for your interest. The input data format is flexible as long as you read the model inputs correctly. You can always convert them to each other. It can be applied to high-dimensional data.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kaiwenzha** [comment]
I do not see the pictures. Are you referring to #18?

**Comment by ytkmy5555** [comment]
Sorry, maybe my internet speed is not good so I didn't send the picture to you successfully. The content described by the picture is the distribution of the data, the red line is the real data distribution(i.e. labels); the blue line is the result prediction by the model. My question is: obviously, the predicted data is closer to the labels, but why does the RMSE and MAE of the test increase? Shouldn't it get smaller?&nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YyzHarry/imbalanced-regression"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月20日(星期天) 中午1:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YyzHarry/imbalanced-regression] Hi @YyzHarry, (Issue #17)





 
I do not see the pictures. Are you referring to #18?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by YyzHarry** [comment]
There's no picture provided; as you are operating on your own data, we don't know what's the actual problem.

Closing this issue for now. Feel free to add comments if you have any related questions.

**Comment by ytkmy5555** [comment]
sorry, I'm still a question want to sak to you: Does the output result of LDS depend on the data value itself or the proportion of data in the data set? I would appreciate it if you could answer for me.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YyzHarry/imbalanced-regression"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月21日(星期一) 凌晨4:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YyzHarry/imbalanced-regression] Hi @YyzHarry, (Issue #17)





 
There's no picture provided; as you are operating on your own data, we don't know what's the actual problem.
 
Closing this issue for now. Feel free to add comments if you have any related questions.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
