### ISSUE TITLE
Implementation of SMOGN and RRT for deep regression

### ISSUE THREAD

**Issue by ackbar03** [YyzHarry/imbalanced-regression#22]
Hi, 

Could you help clarify your implementation for SMOGN and RRT in the paper?

- For SMOGN, did you do the interpolation based on raw images? I.e. simply interpolating between the raw pixel values?
- 
- For RRT, how did you train the encoder step? Do you train the entire model first, and then freeze the encoder and only train the last layer?

Thanks for clarifying!

**Comment by YyzHarry** [comment]
Hi - thanks for your interest!

> For SMOGN, did you do the interpolation based on raw images? I.e. simply interpolating between the raw pixel values?

Yes, the interpolation is done in the input space. More details regarding SMOGN can be found in Section C.1 in [our paper](https://arxiv.org/pdf/2102.09554.pdf).

> For RRT, how did you train the encoder step? Do you train the entire model first, and then freeze the encoder and only train the last layer?

Yes, in the first stage we train the entire model, and in the second stage we freeze the encoder and retrain the last regression layer. You will need to specify a training arg `args.retrain_fc`, [see here](https://github.com/YyzHarry/imbalanced-regression/blob/main/agedb-dir/train.py#L154) for example.
