### ISSUE TITLE
Hi, confusion about the computation of the feature statistics similarity (mean&variance)

### ISSUE THREAD

**Issue by lixingang** [YyzHarry/imbalanced-regression#25]
I'm dealing my unbalanced data with your study; 
A little confusion: how to compute the Feature statistics similarity between the many-shot region and few-shot region? 
Cuz the features in the few-shot region bins are less than that in many-shot region.
![image](https://user-images.githubusercontent.com/29219940/172033989-35f5dff7-2fe9-4f4d-8017-7db14b6d8277.png)

Thanks to your attention!

**Comment by lixingang** [comment]
I'm not sure whether my understanding is correct:
the practice is computing the mean and variance value across the samples in the same bin, and finally each bin owns two features(the feature mean and the feature variance) ?  If so, the issue should be closed.

**Comment by YyzHarry** [comment]
Hi - thanks for your interest. Yes, your understanding is correct -- the feature mean / (co)variance are computed over all samples in the same bin. Then you calculate the similarity between bins.
