### ISSUE TITLE
About SHHS-DIR Code

### ISSUE THREAD

**Issue by weigetang406team** [YyzHarry/imbalanced-regression#27]
hi，SHHS-DIR 的数据需要授权，不便上传。论文中基于该数据集的相关代码方便上传下吗？
谢谢

**Comment by YyzHarry** [comment]
Thanks for your interest. SHHS-DIR related code is currently entangled with other on-going projects, so we do not have a standalone version for now.

However, we have provided detailed descriptions in our paper on data preprocessing & training for SHHS-DIR (e.g., see #7). The code structure and the usage of LDS/FDS are very similar to other DIR datasets, which you can refer to.
