### ISSUE TITLE
I have a question about training a model using RRT 

### ISSUE THREAD

**Issue by linchuanze** [YyzHarry/imbalanced-regression#30]
Do i need set a few epoch to traing the last regressor.As shown in the figure below, what causes it
![屏幕截图 2022-10-05 200438](https://user-images.githubusercontent.com/50792806/194056328-99600675-1315-4138-95c7-46bfc3709ba3.png)

**Comment by YyzHarry** [comment]
Hi, for RRT you can follow the command
```bash
python train.py [...retrained model arguments...] --retrain_fc --pretrained <path_to_pretrained_ckpt>
```

For RRT, the hyper-parameter settings remain the same between the first and the second training stage, though one usually trains for fewer epochs as only last layer is trained (e.g., 10/30 epochs for age datasets). See examples & descriptions from, for example, [AgeDB-DIR](https://github.com/YyzHarry/imbalanced-regression/tree/main/agedb-dir).
