### ISSUE TITLE
On the implementation of SMOTER and SMOGN algorithms in the paper

### ISSUE THREAD

**Issue by GXNU156489** [YyzHarry/imbalanced-regression#33]
@YyzHarry Hello, I would like to ask, how did you implement the SMOTER and SMOGN algorithms in the paper? Are there parameters in the code to call them?

**Comment by YyzHarry** [comment]
Hi - thanks for your interest. For SMOGN, the interpolation is done in the input space.

More details regarding SMOGN can be found in Section C.1 in [our paper](https://arxiv.org/pdf/2102.09554.pdf).
