### ISSUE TITLE
The reproduced benchmark and model seem to be damaged

### ISSUE THREAD

**Issue by GXNU156489** [YyzHarry/imbalanced-regression#34]
Hi @YyzHarry ，The reproduced benchmark and model seem to be damaged。I use this link（ https://drive.google.com/file/d/1CPDlcRCQ1EC4E3x9w955cmILSaVOlkyz/view ）The downloaded model cannot be opened. It indicates that the data has been damaged. Can you update the model? Thank you！

**Comment by kaiwenzha** [comment]
Hi @GXNU156489 Thank you for your interest in our work! We tested the model you referred to and found it could be loaded and give out the correct results. Could you please try the following script to see whether it works or not:
`CUDA_VISIBLE_DEVICES=0,1,2,3 python train.py --reweight sqrt_inv --lds --lds_kernel gaussian --lds_ks 5 --lds_sigma 2 --data_dir [path to your data folder] --evaluate --resume [path to the checkpoint]`

**Comment by GXNU156489** [comment]
> 你好@GXNU156489感谢您对我们的工作感兴趣！我们测试了您提到的模型，发现它可以加载并给出正确的结果。能否请您尝试以下脚本，看看它是否有效： `CUDA_VISIBLE_DEVICES=0,1,2,3 python train.py --reweight sqrt_inv --lds --lds_kernel gaussian --lds_ks 5 --lds_sigma 2 --data_dir [path to your data folder] --evaluate --resume [path to the checkpoint]`

thanks for your answer！
