### ISSUE TITLE
SHHS dataset

### ISSUE THREAD

**Issue by Google0007** [YyzHarry/imbalanced-regression#37]
Excuse me. 
Is it convenient to provide the SHHS data and its preprocessing scripts?
Thank you advance!

**Comment by YyzHarry** [comment]
The SHHS-DIR dataset is based on the original [SHHS dataset](https://sleepdata.org/datasets/shhs) -- which you will need to apply for the data access.

Once you get the data ready, you can create SHHS-DIR by following the instructions in Appendix B & C (also see Table 7 for detailed number) in our [paper](https://arxiv.org/pdf/2102.09554.pdf). See also https://github.com/YyzHarry/imbalanced-regression/issues/7 & https://github.com/YyzHarry/imbalanced-regression/issues/27.
