### ISSUE TITLE
bucket_num bucket_start

### ISSUE THREAD

**Issue by wklix** [YyzHarry/imbalanced-regression#38]
Would you please tell me how to choose the best bucket_num and bucket_start parameters?The range of labels in my dataset is (-2, 16)

**Comment by YyzHarry** [comment]
Hi, thanks for your interest. The choice of `bucket_num` & `bucket_start` will depend on the (minimum) resolution you care about for your task. For example, in age prediction, the minimum interval we care about is 1 (year), so we chose bucket_num accordingly.
