### ISSUE TITLE
Negative Age

### ISSUE THREAD

**Issue by Holmes2002** [YyzHarry/imbalanced-regression#39]
Hi, I run inference with your checkpoint but all my outputs are negative ?
Y said that You hadn't used any preprocess with labels right ?

**Comment by YyzHarry** [comment]
We did not apply preprocessing to the age prediction labels in our methodology. Additionally, there have been no reports of issues regarding negative outputs from either our team or others in this field. Given the lack of further information on this matter, I am closing this issue. However, please feel free to provide additional details or raise new concerns if necessary.
