### ISSUE TITLE
Smooth Z calculation

### ISSUE THREAD

**Issue by rohanpaul14855** [YyzHarry/imbalanced-regression#4]
In equation 6 of the paper (calculating the smoothed z), what is the subscript b referring to? From my understanding, it is the target bucket for the specific example from which z was calculated. If so, how is this implemented at test time? Wouldn't we require knowledge of the bin to which the example belongs?

It appears that the FDS layer accesses the label too: https://github.com/YyzHarry/imbalanced-regression/blob/dc7ae76bc62a9d322617b60ff1f23b5e0876783d/agedb-dir/fds.py#L119

Feels like I'm misunderstanding something

**Comment by YyzHarry** [comment]
Hi, thank you for your interest!
> From my understanding, it is the target bucket for the specific example from which z was calculated.

Yes, your understanding is correct, b is the target bucket.

> If so, how is this implemented at test time?

Good question. Actually, during inference, the FDS module is not enabled:
https://github.com/YyzHarry/imbalanced-regression/blob/dc7ae76bc62a9d322617b60ff1f23b5e0876783d/agedb-dir/resnet.py#L142-L144

Adding FDS module during training can implicitly regularize the model to learn to generate features that are more accurate even without smoothing, and finally the smoothing module can be removed during inference (the L1 distance between the running statistics and the smoothed statistics during training will gradually diminish to near zero). More details can be found in the [paper](https://arxiv.org/pdf/2102.09554.pdf) on page 8, "Understanding FDS" part (and Figure 8).

Hope this helps. Let me know if you have any questions!
