### ISSUE TITLE
move get_transform to __init__

### ISSUE THREAD

**Issue by LiuNingtao** [YyzHarry/imbalanced-regression#40]
Hi,

Thank you for your great work.

A little suggestion,  probably you can move the data transforms to the __init__ of the dataset class instead of invoking the _get_transform_ each time get data. 

I think this would be better to improve the speed of preparing the data and hope this is helpful for you.

Thank you.

Ningtao

School of AI, Xidian University, China
Robarts Research Institute, Western University, Canada

**Comment by YyzHarry** [comment]
Hi Ningtao, thanks for your interest in our work. Your suggestion sounds interesting, but due to limited bandwidth, we will not be looking into it for now. We welcome contributions, so if you're able to test and validate the improvements, please consider submitting a pull request.
