### ISSUE TITLE
How Interpolation and Extrapolation works?

### ISSUE THREAD

**Issue by saranadeem01** [YyzHarry/imbalanced-regression#41]
Hi @YyzHarry,

I hope this message finds you well. I am reaching out to you regarding your paper, specifically about the discussion on interpolation and extrapolation of sample labels. While reviewing the code, I couldn't understand whether this functionality is implemented as a separate module or if the same LDS and FDS symmetric kernel is utilized for this purpose as well.

Could you kindly provide clarification or guidance on this matter? Many thanks.

**Comment by YyzHarry** [comment]
Hi, thank you for your interest! Interpolation and extrapolation are key _benefits_ offered by LDS and FDS. These methods particularly enhance learning in imbalanced regression settings, leading to improved generalization for unseen targets as a result. For detailed results on interpolation and extrapolation, please refer to Section 4.2 in our paper.
