### ISSUE TITLE
feature smoothing when doing backward propogation 

### ISSUE THREAD

**Issue by TerenceChen95** [YyzHarry/imbalanced-regression#6]
Hi, thanks for sharing this wonderful project! There's a small question I wanna ask for. I got the following error when applying the FDS module:

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [64]], which is output 0 of SelectBackward, is at version 7; expected version 3 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

When I add feature.detach(), the error was gone, but if it is correct to do so? From my understanding, this module is updating feature with previous means and vairances, does it affect the BP part? Thanks in advance for any help!

**Comment by kaiwenzha** [comment]
Hi @TerenceChen95, thanks for your interest!

I guess you were trying to apply FDS to your own model/data since our code will not raise this error. Would you mind sharing the specific code snippet related to the issue so that we can better help you. It seems that the problem was caused by the inplace operation when smoothing the features.

**Comment by qingzhu0214** [comment]
> Hi @TerenceChen95, thanks for your interest!
> 
> I guess you were trying to apply FDS to your own model/data since our code will not raise this error. Would you mind sharing the specific code snippet related to the issue so that we can better help you. It seems that the problem was caused by the inplace operation when smoothing the features.

Hi @kaiwenzha  
I encountered the same problem, this is my code. May I trouble you to see what caused it？Thank you in advance！！
`class MLP(nn.Module):
    def __init__(self, input_dim, output_dim, hidden_dim, **config):
        super(MLP, self).__init__()
        self.input_layer = nn.Sequential(nn.Linear(input_dim, hidden_dim), nn.ReLU(False))
        self.hidden_layer1 = nn.Sequential(nn.Linear(hidden_dim, hidden_dim), nn.ReLU(False))
        self.hidden_layer2 = nn.Sequential(nn.Linear(hidden_dim, hidden_dim), nn.ReLU(False))
        self.output_layer = nn.Sequential(nn.Linear(hidden_dim, output_dim))
        self.FDS = FDS(**config)
    def forward(self, x, labels, epoch):
        x = self.input_layer(x)
        x = nn.Dropout(0.2)(x)
        x = self.hidden_layer1(x)
        x = nn.Dropout(0.2)(x)
        x = self.hidden_layer2(x)
        features = x
        smoothed_features = x
        if self.training and epoch >= config['start_smooth']:
            smoothed_features = self.FDS.smooth(features, labels, epoch)
        x = self.output_layer(smoothed_features)
        return x, features
    def initialize(self):
        for m in self.modules():
            if isinstance(m, nn.Linear):
                nn.init.kaiming_normal_(m.weight.data)

from fds import FDS
hidden_dim = 32
config = dict(feature_dim=hidden_dim, start_update=0, start_smooth=1, kernel='gaussian', ks=5, sigma=2)

train_dataloader = DataLoader(train_dataset,
                               batch_size=16,
                               shuffle=True,
                               num_workers=0)
num_epoches = 100
learning_rate = 0.001
expert_model = MLP(9,1,hidden_dim,**config)
if torch.cuda.is_available():
    expert_model = expert_model.cuda()
expert_model.initialize()

mseloss = nn.MSELoss()
optimizer = torch.optim.Adam(expert_model.parameters(),lr=learning_rate,betas=(0.9,0.99),weight_decay=0.001)        

for epoch in range(num_epoches):

    expert_model.train()
    for data, target in train_dataloader:
        output, features = expert_model(data, target, epoch)
        loss = mseloss(output,target)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    
    expert_model.eval()
    output, train_features = expert_model(train_data, train_label, epoch)

    if epoch >= config['start_update']:
        expert_model.FDS.update_last_epoch_stats(epoch)
        expert_model.FDS.update_running_stats(train_features, train_label.reshape(-1), epoch)`

**Comment by carlotapares** [comment]
Hi @kaiwenzha, I am also getting the same issue. I attach the code snippet that is causing it. 

```
def smooth(self, features, labels, epoch):
        if epoch < self.start_smooth:
            return features
        labels = labels.squeeze(1)
        buckets = np.array([self._get_bucket_idx(label) for label in labels])
        for bucket in np.unique(buckets):
            features[buckets == bucket] = calibrate_mean_var(
                features[buckets == bucket],
                self.running_mean_last_epoch[bucket],
                self.running_var_last_epoch[bucket],
                self.smoothed_mean_last_epoch[bucket],
                self.smoothed_var_last_epoch[bucket]
            )
        return features
```

The assignment to an existing tensor `features[buckets == bucket] =`  raises the error.
Thanks in advance for your help!

**Comment by 907491795** [comment]
Hi @carlotapares ，I am also getting the same issue.  Have you solved this problem？

**Comment by ChengkaiYang** [comment]
> Hi @kaiwenzha, I am also getting the same issue. I attach the code snippet that is causing it.
> 
> ```
> def smooth(self, features, labels, epoch):
>         if epoch < self.start_smooth:
>             return features
>         labels = labels.squeeze(1)
>         buckets = np.array([self._get_bucket_idx(label) for label in labels])
>         for bucket in np.unique(buckets):
>             features[buckets == bucket] = calibrate_mean_var(
>                 features[buckets == bucket],
>                 self.running_mean_last_epoch[bucket],
>                 self.running_var_last_epoch[bucket],
>                 self.smoothed_mean_last_epoch[bucket],
>                 self.smoothed_var_last_epoch[bucket]
>             )
>         return features
> ```
> 
> The assignment to an existing tensor `features[buckets == bucket] =` raises the error. Thanks in advance for your help!

You can solve the problem by using torch.masked_scatter function and will get no longer inplace operation.
I think the inplace latent problem is here:
feature[labels == label] = self.carlibarate(feature[labels==label])
Maybe we must use torch.masked_scatter function to fix the problem like following:
`features = torch.masked_scatter(features,(labels == label).unsqueeze(1).repeat(1,features.shape[1]),self.calibrate_mean_var( features[labels == label], self.running_mean_last_epoch[int(label - self.bucket_start)], self.running_var_last_epoch[int(label - self.bucket_start)], self.smoothed_mean_last_epoch[int(label - self.bucket_start)], self.smoothed_var_last_epoch[int(label - self.bucket_start)]))`

**Comment by ChengkaiYang** [comment]
> You can solve the problem by using torch.masked_scatter function and will get no longer inplace operation.

You can solve the problem by using torch.masked_scatter function and will get no longer inplace operation.
I think the inplace latent problem is here:
feature[labels == label] = self.carlibarate(feature[labels==label])
Maybe we must use torch.masked_scatter function to fix the problem like following:
`features = torch.masked_scatter(features,(labels == label).unsqueeze(1).repeat(1,features.shape[1]),self.calibrate_mean_var( features[labels == label], self.running_mean_last_epoch[int(label - self.bucket_start)], self.running_var_last_epoch[int(label - self.bucket_start)], self.smoothed_mean_last_epoch[int(label - self.bucket_start)], self.smoothed_var_last_epoch[int(label - self.bucket_start)]))`

**Comment by ChengkaiYang** [comment]
> Hi @TerenceChen95, thanks for your interest!
> 
> I guess you were trying to apply FDS to your own model/data since our code will not raise this error. Would you mind sharing the specific code snippet related to the issue so that we can better help you. It seems that the problem was caused by the inplace operation when smoothing the features.

Yes, I think the inplace latent problem is here:
feature[labels == label] = self.carlibarate(feature[labels==label])
Maybe we must use torch.masked_scatter function to fix the problem like following:
`features = torch.masked_scatter(features,(labels == label).unsqueeze(1).repeat(1,features.shape[1]),self.calibrate_mean_var( features[labels == label], self.running_mean_last_epoch[int(label - self.bucket_start)], self.running_var_last_epoch[int(label - self.bucket_start)], self.smoothed_mean_last_epoch[int(label - self.bucket_start)], self.smoothed_var_last_epoch[int(label - self.bucket_start)]))`
