### ISSUE TITLE
About SHHS-DIR dataset

### ISSUE THREAD

**Issue by axi345** [YyzHarry/imbalanced-regression#7]
Thanks a lot for your contribution, your works are really awesome. 
I am very interested in your work. However, during the code reading, I did not find the SHHS-DIR dataset. 
Could you publish the SHHS-DIR dataset or its sampling method, thank you!

**Comment by YyzHarry** [comment]
Hi - thanks for your interest! The SHHS-DIR dataset is based on the original [SHHS dataset](https://sleepdata.org/datasets/shhs) -- which you will need to apply for the data access. Once you get the data ready, you can create SHHS-DIR by following the instructions in Appendix B & C (also see Table 7 for detailed number) in our [paper](https://arxiv.org/pdf/2102.09554.pdf).

**Comment by ytkmy5555** [comment]
作者您好，首先特别感谢您把工作发表出来，我对您的工作特别感兴趣。但是，我尝试了很多方法，代码就是跑不通，这怎么回事呢

**Comment by ytkmy5555** [comment]
Hi Dr.Yang
&nbsp; &nbsp;&nbsp;I am particularly interested in your work of imbalanced regression，and I want to use your method， such as LDS，to deal with my problems；but there are some problems bothering me，do you code of LDS have any requirements for the format of input data？does the weight of data refer to the ratio of a certain data in the original data？Can I directly apply your code with a small modification? For example:
&nbsp; &nbsp;&nbsp;def _prepare_weights(labels, reweight, max_target=121, lds=False, lds_kernel='gaussian', lds_ks=5, lds_sigma=2):
    assert reweight in {'none', 'inverse', 'sqrt_inv'}
    assert reweight != 'none' if lds else True, \
        "Set reweight to \'sqrt_inv\' (default) or \'inverse\' when using LDS"

    value_dict = {x: 0 for x in range(max_target)}
    # labels = self.df['age'].values
    for label in labels:
        value_dict[min(max_target - 1, int(label))] += 1
    if reweight == 'sqrt_inv':
        value_dict = {k: np.sqrt(v) for k, v in value_dict.items()}
    elif reweight == 'inverse':
        value_dict = {k: np.clip(v, 5, 1000) for k, v in value_dict.items()}  # clip weights for inverse re-weight
    num_per_label = [value_dict[min(max_target - 1, int(label))] for label in labels]
    if not len(num_per_label) or reweight == 'none':
        return None
    print(f"Using re-weighting: [{reweight.upper()}]")

    if lds:
        lds_kernel_window = get_lds_kernel_window(lds_kernel, lds_ks, lds_sigma)
        print(f'Using LDS: [{lds_kernel.upper()}] ({lds_ks}/{lds_sigma})')
        smoothed_value = convolve1d(
            np.asarray([v for _, v in value_dict.items()]), weights=lds_kernel_window, mode='constant')
        num_per_label = [smoothed_value[min(max_target - 1, int(label))] for label in labels]

    weights = [np.float32(1 / x) for x in num_per_label]
    scaling = len(weights) / np.sum(weights)
    weights = [scaling * x for x in weights]
    return weightsdef main():
    data = np.load(r'C../train_data_40days_unnorm.npz', header=None, delimiter=',', low_memory=False).
    labels = data[:,3]

    weights = _prepare_weights(labels, reweight='sqrt_inv', lds=True, lds_kernel='gaussian', lds_ks=5, lds_sigma=2)

    return

if __name__ == '__main__':I would appreciate it if you could give me some guidance。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YyzHarry/imbalanced-regression"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月29日(星期六) 中午12:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YyzHarry/imbalanced-regression] About SHHS-DIR dataset (#7)





 
Closed #7.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
